# Generated by Django 3.2.8 on 2021-10-07 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='follower',
        ),
        migrations.AddField(
            model_name='follow',
            name='followedBy',
            field=models.CharField(default='0 ', max_length=5000),
        ),
        migrations.AddField(
            model_name='follow',
            name='who',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
        migrations.AlterField(
            model_name='follow',
            name='following',
            field=models.CharField(default='0 ', max_length=5000),
        ),
    ]
